django_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pages.urls")),
]

pages/urls.py
from django.urls import path
from .views import (
    form_page_view,
    HomePageView,
    AboutPageView,
    SearchResultsView,
    ou_profile_view,
)
from . import views


urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("about/", AboutPageView.as_view(), name="about"),
    path("form/", form_page_view, name="form"),
    path("search/", SearchResultsView.as_view(), name="search_results"),
    path("profile/<int:registrikood>", ou_profile_view, name="profile"),
]

pages/models.py
from datetime import date
from django.db import models
from django.forms import ValidationError
import re

# Create your models here.


class OsanikModel(models.Model):
    nimi = models.TextField(null=False)
    kood = models.CharField(max_length=11)

    def __str__(self):
        return self.nimi + " - " + str(self.kood)


class OsauhinguAndmedModel(models.Model):
    def validate_nimi(name):
        if len(name) < 3 or len(name) > 100:
            raise ValidationError("Nimi peab olema 3 kuni 100 tähte või numbrit pikk")

    def validate_registrikood(kood):
        if len(kood) != 7 and not re.match(r"^([\d]+)$", kood):
            raise ValidationError("Registrikood peab olema 7 numbrit pikk")

    def validate_asutamiskp(kp):
        if kp > date.today():
            raise ValidationError(
                "Asutamiskuupäev peab olema väiksem või võrdne tänasega"
            )

    def validate_kapital(kapital):
        if not re.match(r"^([\d]+)$", str(kapital)) and int(kapital) < 2500:
            raise ValidationError(
                "Kogukapital peab olema summa eurodes ja mitte väiksem kui 2500"
            )

    nimi = models.TextField(null=False, blank=False, validators=[validate_nimi])
    registrikood = models.CharField(
        null=False,
        blank=False,
        unique=True,
        max_length=7,
        validators=[validate_registrikood],
    )
    asutamiskp = models.DateField(
        blank=False,
        validators=[validate_asutamiskp],
    )
    kapital = models.PositiveIntegerField(
        null=False, blank=False, default=5000, validators=[validate_kapital]
    )
    osanikud = models.ManyToManyField(OsanikModel, through="Osalus")

    def __str__(self) -> str:
        return self.nimi + ": " + str(self.registrikood)


class Osalus(models.Model):
    def validate_osaluse_suurus(osaluse_suurus):
        if osaluse_suurus < 1:
            raise ValidationError("Osaluse suurus peab olema suurem või võrdne 1ga")

    person = models.ForeignKey(OsanikModel, on_delete=models.CASCADE)
    company = models.ForeignKey(OsauhinguAndmedModel, on_delete=models.CASCADE)
    osaluse_suurus = models.PositiveIntegerField(validators=[validate_osaluse_suurus])
    asutaja = models.BooleanField(default=False)

pages/forms.py
from django import forms
from .models import OsauhinguAndmedModel


class OsauhinguAndmedForm(forms.ModelForm):
    class Meta:
        model = OsauhinguAndmedModel
        exclude = ("osanikud",)

pages/views.py
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.generic import TemplateView, ListView
from pages.forms import OsauhinguAndmedForm
from pages.models import Osalus, OsauhinguAndmedModel
from django.db.models import Q


# Create your views here.
class HomePageView(ListView):
    model = OsauhinguAndmedModel
    template_name = "avaleht.html"


class AboutPageView(TemplateView):
    template_name = "about.html"


class SearchResultsView(ListView):
    model = OsauhinguAndmedModel
    template_name: str = "search.html"

    def get_queryset(self):
        query = self.request.GET.get("q")
        return OsauhinguAndmedModel.objects.filter(
            Q(nimi__icontains=query)
            | Q(registrikood__icontains=query)
            | Q(osanikud__nimi__icontains=query)
            | Q(osanikud__kood__icontains=query)
        ).distinct()


def form_page_view(request):
    context = {}
    osalusFormset = inlineformset_factory(
        OsauhinguAndmedModel,
        Osalus,
        fields=("person", "osaluse_suurus", "asutaja"),
        extra=1,
    )
    if request.method == "POST":
        form = OsauhinguAndmedForm(request.POST)
        formset = osalusFormset(request.POST)
        if form.is_valid() and formset.is_valid():
            sum_segments = 0
            for segment_form in formset:
                if segment_form.cleaned_data["osaluse_suurus"]:
                    cleaned_segment = segment_form.cleaned_data["osaluse_suurus"]
                    sum_segments += int(cleaned_segment)
            kapital = int(form.cleaned_data["kapital"])
            if kapital == sum_segments:
                ou_instance = form.save()
                osalused = formset.save(commit=False)
                for osalus in osalused:
                    osalus.company = ou_instance
                    osalus.save()
                return redirect("profile", registrikood=ou_instance.registrikood)
    form = OsauhinguAndmedForm()
    formset = osalusFormset()
    context["form"], context["formset"] = form, formset
    return render(request, "form.html", context)


def ou_profile_view(request, registrikood):
    context = {}
    osauhing = get_object_or_404(OsauhinguAndmedModel, registrikood=registrikood)
    osanikud = []
    for osanik in osauhing.osanikud.all():
        nimi = osanik.nimi
        kood = osanik.kood
        osalus = osanik.osalus_set.get(company=osauhing)
        osa_suurus = osalus.osaluse_suurus
        asutaja = "Asutaja" if osalus.asutaja else ""
        osanikud.append([nimi, kood, osa_suurus, asutaja])
    context["ou"] = osauhing
    context["osanikud"] = osanikud
    return render(request, "profile.html", context)

templates/about.html
{% extends "base.html" %} {% block content %}
<h1>Infot leheküljest</h1>
<t
  >Leht on tehtud oskuste demonstreerimiseks ja ei sisalda reaalelulisi
  näiteid.</t
>
{% endblock content %}

templates/asutajad.html
{% extends "base.html" %} {% load static %} {% block content %}
<head>
  <title>Avaleht</title>
  <link rel="stylesheet" href="{% static 'pages/css/style.css' %}" />
</head>
<body class="content">
  <p>Veenduge, et osanike osade suurus oleks kokku {{ kapital }}</p>
  <form method="post">
    {% csrf_token %} {{ formset.as_p }}
    <input type="submit" value="Lisa asutaja" />
  </form>
  <div class="right">
    <div class="search">
      Otsi olemasolevat asutajat
      <form method="get">
        <input name="search" type="text" placeholder="Otsi..." />
      </form>
    </div>
    {% for search_result in search_results %}
    <p class="full_length">{{search_result}}</p>
    {% endfor %}
  </div>
</body>
{% endblock content %}

templates/avaleht.html
{% extends "base.html" %} {% load static %} {% block content %}
<head>
  <title>Avaleht</title>
  <link rel="stylesheet" href="{% static 'pages/css/style.css' %}" />
</head>
<body class="content">
  <div class="search">
    Otsi osaühingut
    <form action="{% url 'search_results' %}" method="get">
      <input name="q" type="text" placeholder="Otsi..." />
    </form>
  </div>
  <ul>
    {% for andmed in osauhinguandmedmodel_list %}
    <li>
      <div
        class="selective"
        onclick="location.href='{% url 'profile' registrikood=andmed.registrikood%}'"
      >
        <p class="selectedLink">Osaühing: {{ andmed.nimi }}</p>
        <p>Registrikood: {{andmed.registrikood}}</p>
      </div>
    </li>
    {% endfor %}
  </ul>
</body>
{% endblock content %}

templates/base.html
{% load static %}
<link rel="stylesheet" href="{% static 'pages/css/headerStyle.css' %}" />
<link rel="stylesheet" href="{% static 'pages/css/style.css' %}" />

<div class="header" id="baseHeader">
  <h2>
    <a class="headerLink" href="{% url 'home' %}">Avaleht</a>
    <a class="headerLink" href="{% url 'form' %}">Osaühingu asutamise vorm</a>
    <a class="headerLink" href="{% url 'about' %}">About</a>
  </h2>
</div>

{% block content %} {% endblock content %}

templates/form.html
{% extends "base.html" %} {% load static %} {% block content %}
<head>
  <title>Asutamisvorm</title>
  <link rel="stylesheet" href="{% static 'pages/css/style.css' %}" />
  <script src="{% static 'pages/js/jquery-3.6.0.min.js' %}">
      </script
    <script src="{% static 'pages/js/my-jquery.js' %}">
  </script>
</head>
<body class="content">
  <p>Asutamise kuupäev märkida formaadis AASTA-KUU-PÄEV</p>
  <p>Näide: 21. juuni 2010 oleks 2010-06-21</p>
  <form id="form-container" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    {{ formset.management_form }} {% for f in formset %}
    <div class="osalus-form">
      <table class="no-error">
        {{f.as_table}}
      </table>
    </div>
    {%endfor%}
    <button id="add_more" type="button">Lisa osanik</button>
    <input type="submit" value="Salvesta" />
  </form>
</body>

<script>
  $("#add_more").click(function () {
    cloneMore("div.osalus-form:last", "osalus_set");
  });

  function cloneMore(selector, type) {
    var newElement = $(selector).clone(true);
    var total = $("#id_" + type + "-TOTAL_FORMS").val();
    newElement.find(":input").each(function () {
      var name = $(this)
        .attr("name")
        .replace("-" + (total - 1) + "-", "-" + total + "-");
      var id = "id_" + name;
      $(this).attr({ name: name, id: id }).val("").removeAttr("checked");
    });
    newElement.find("label").each(function () {
      var newFor = $(this)
        .attr("for")
        .replace("-" + (total - 1) + "-", "-" + total + "-");
      $(this).attr("for", newFor);
    });
    total++;
    $("#id_" + type + "-TOTAL_FORMS").val(total);
    $(selector).after(newElement);
  }
</script>
{% endblock content %}

templates/profile.html
{% extends "base.html" %} {% block content %}
<title>{{ou.nimi}} andmete vaade</title>
<h1>{{ou.nimi}} andmete vaade</h1>
<p>Nimi: {{ ou.nimi }}</p>
<p>Registrikood: {{ ou.registrikood }}</p>
<p>Asutamiskuupäev: {{ ou.asutamiskp }}</p>
<p>Kapital: {{ ou.kapital }}</p>
{% if osanikud %}
<br />
<p>Osanikud:</p>
<br />
{% for osanik in osanikud %} {% for osa in osanik %}
<p>{{ osa }}</p>
{% endfor %}
<br />
{%endfor %} {% else %}
<p>Osanikke ei leitud</p>
{% endif %} {% endblock content %}

templates/search.html
{% extends "base.html" %} {% block content %}
<div class="content">
  <h1>Search results</h1>
  <ul>
    {% for andmed in object_list %}
    <li>
      <div
        class="selective"
        onclick="location.href='{% url 'profile' registrikood=andmed.registrikood%}'"
      >
        <p class="selectedLink">Osaühing: {{ andmed.nimi }}</p>
        <p>Registrikood: {{andmed.registrikood}}</p>
      </div>
    </li>
    {% endfor %}
  </ul>
</div>
{% endblock content %}